from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator
from django.utils import timezone
from django.core.exceptions import ValidationError

class Categories(models.Model):
    # id is auto-generated by django
    name = models.CharField(max_length=100, verbose_name='カテゴリー名')
    description = models.TextField(blank=True, null=True, verbose_name='説明')
    is_expense = models.BooleanField(default=True, verbose_name='支出カテゴリー')
    created_by = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='作成者',
        related_name='categories_created_by',
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='作成日時')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='更新日時')

    class Meta:
        verbose_name = 'カテゴリー'
        ordering = ['id']


class Expenses(models.Model):
    # id is auto-generated by django
    user = models.ForeignKey(
        User, 
        on_delete=models.CASCADE, 
        verbose_name='ユーザー',
        related_name='expenses_user',
    )
    category = models.ForeignKey(
        Categories, 
        on_delete=models.CASCADE, 
        verbose_name='カテゴリー',
        related_name='expenses_category',
        limit_choices_to={'is_expense': True},  # 支出カテゴリーのみ
    )
    amount = models.IntegerField(
        validators=[MinValueValidator(0)],
        verbose_name='金額'
    )
    description = models.TextField(null=True, verbose_name='説明')
    date = models.DateField(default=timezone.now, verbose_name='日付')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='作成日時')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='更新日時')

    class Meta:
        verbose_name = '支出'
        ordering = ['id']
    
    def clean(self):
        super().clean()
        if self.category and not self.category.is_expense:
            raise ValidationError({
                'category': '支出には支出カテゴリーを選択してください。'
            })


class Incomes(models.Model):
    # id is auto-generated by django
    user = models.ForeignKey(
        User, 
        on_delete=models.CASCADE, 
        verbose_name='ユーザー',
        related_name='incomes_user',
    )
    category = models.ForeignKey(
        Categories, 
        on_delete=models.CASCADE, 
        verbose_name='カテゴリー',
        related_name='incomes_category',
        limit_choices_to={'is_expense': False},  # 収入カテゴリーのみ
    )
    amount = models.IntegerField(
        validators=[MinValueValidator(0)],
        verbose_name='金額'
    )
    description = models.TextField(null=True, verbose_name='説明')
    date = models.DateField(default=timezone.now, verbose_name='日付')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='作成日時')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='更新日時')

    class Meta:
        verbose_name = '収入'
        ordering = ['id']
    
    def clean(self):
        super().clean()
        if self.category and self.category.is_expense:
            raise ValidationError({
                'category': '収入には収入カテゴリーを選択してください。'
            })


class Budgets(models.Model):
    # id is auto-generated by django
    PERIOD_CHOICES = [
        ('daily', '日次'),
        ('weekly', '週次'),
        ('monthly', '月次'),
        ('yearly', '年次'),
    ]

    user = models.ForeignKey(
        User, 
        on_delete=models.CASCADE, 
        verbose_name='ユーザー',
        related_name='budgets_user',
    )
    category = models.ForeignKey(
        Categories, 
        on_delete=models.CASCADE, 
        verbose_name='カテゴリー',
        related_name='budgets_category',
    )
    description = models.TextField(null=True, verbose_name='説明')
    amount = models.IntegerField(
        validators=[MinValueValidator(0)],
        verbose_name='予算額'
    )
    period = models.CharField(
        max_length=10,
        choices=PERIOD_CHOICES,
        default='monthly',
        verbose_name='期間'
    )
    start_date = models.DateField(verbose_name='開始日')
    end_date = models.DateField(verbose_name='終了日')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='作成日時')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='更新日時')

    class Meta:
        verbose_name = '予算'
        ordering = ['id']
